---
title: "Start with the literature: assessthe empirical evidence for the relationship between ter-rorism and political attitudes"
author: "Bernice(Yixuan) Bao, Zheng(Zeb) Yang, Jingcheng Yang"
thanks: "Code and data are available at: https://github.com/BerniceBao/Terrorism-Political-Attitude ; Replication on Social Science Reproduction platform available at: https://doi.org/10.48152/ssrp-qg85-cb34"
date: "February 13, 2024"
date-format: long
format: 
  pdf: 
    include-in-header: 
      text: |
        \usepackage{lscape}
        \newcommand{\blandscape}{\begin{landscape}}
        \newcommand{\elandscape}{\end{landscape}}
    documentclass: article
    geometry: margin = 1in
    abstract: "Immigration and asylum-seeking are common topics of discussion in our globalized world, about which many Westerners hold opinions due to certain personal justifications. This paper replicates data analysis of the perceptions of non-immigrant German males towards refugees in municipalities where males overpopulate females. We apply secondary research regarding Canadian rates of immigration and gender imbalances in Alberta and raise concerns regarding the possibly generalizable nature of the findings in Germany. As this issue specifically affects minority groups experiencing prejudice, we place great emphasis on the weight of this discussion and call for future investigations of this field to inform policies and initiatives to address racism and hate crimes."
    number-sections: true
output: 
  bookdown::pdf_document2
toc: false
fig_caption: yes
nocite: '@*'
bibliography: references.bib
---

```{r setup}
#| echo: false
#| message: false
#| warning: false
# install.packages('readr')
# install.packages('here')
# install.packages("readstata13")  #  readstata13_0.9.2
# install.packages("MASS") # MASS_7.3-51.6  
# install.packages("sandwich")  # sandwich_2.5-1 
# install.packages("lmtest") # lmtest_0.9-37 
# install.packages("pBrackets") # pBrackets_1.0  
# install.packages("dplyr") 
# install.packages("tidyverse")
# install.packages("list")
# install.packages("knitr")
# install.packages("kableExtra")

library(readr) # read_csv
library(here) # here
library(readstata13) #  readstata13_0.9.2
library(MASS) # MASS_7.3-51.6  
library(sandwich)  # sandwich_2.5-1 
library(lmtest) # lmtest_0.9-37  
library(dplyr)
library(tidyverse)
library(jtools)
library(huxtable)
library(list)
library(knitr)
library(kableExtra)
```

# Introduction

In Canada, hate crimes based on race and ethnicity increased by 80% in 2020, with the highest number of incidents targeting black individuals, followed by east and southeast Asians, indigenous individuals, and the lowest number of victims being South Asian individuals [@moreau_wang_2022]. Seeing that Canada is one of the most diverse countries in the world, welcoming 405,999 permanent immigrants in 2021 [@government_of_canada_2022] and 130,125 refugees in 2020 [@macrotrends], these statistics concerning the increase of hate crimes pose a real and visceral threat to a large proportion of Canadian residents.

There are many factors that contribute to the increase in hate crimes in Canada. However, with the rise of far-right discourse in the United States, anti-immigrant and anti-refugee rhetoric is becoming more prevalent in Canada. These negative attitudes and actions towards immigrants, refugees, and marginalized individuals can be the result of various structural and personal factors, including increased competition in the job and housing markets, resource scarcity, misguided beliefs about crime rates, illness, welfare dependency, and fears of losing national identity. Despite this, one factor that has received little attention until recently is the impact of mate competition in dating and marriage markets on anti-refugee sentiments. A [-@main_paper] paper by Dancygier, Egami, Jamal, and Rischke published in the American Journal of Political Science delves into this potentially important and often-overlooked fusion of social science with ecology.

In studying the opinions of German males living in municipalities with excess male populations, they find that a portion of non-immigrant German men hold the belief that refugees pose a threat to their ability to pursue German women [@main_paper]. The study population is primarily non-immigrant German males in highly male populated municipalities. The estimand which we intend to replicate is the effect of mate competition on anti-refugee sentiments. Their finding suggests that hate crimes increase where non-immigrant German men are disadvantaged in their local dating markets [@main_paper]. Using ecological evidence and originally curated survey data, the paper concludes that competition in dating and marriage markets where men outnumber women increases anti-refugee sentiments and violence [@main_paper].

Our paper will follow a reproduction of Dancygier, Egami, Jamal, and Rischke's findings and apply a Canadian-facing lens to discuss its implications on local Canadian populations and increased anti-refugee/ immigrant sentiments and violence. Our paper seeks to replicate their two following research claims, (1) Non-immigrant German men who live in municipalities with excess male populations are more likely to perceive refugees as threats and (2) Non-immigrant German men who perceive mate competition are more likely to support violence as the only means to gain the attention of German politicians. Our reproduction was conducted using the statistical programming language R [@citeR]. To further enable our analysis we employed the use of the following packages: readr [@readr], here [@here], readstata13 [@readstata13], MASS [@MASS], sandwich [@sandwich], lmtest [@lmtest], dplyr [@dplyr], tidyverse [@tidyverse], jtools [@jtools], huxtable [@huxtable], list [@list], knitr [@knitr] and kableExtra [@kableExtra].

We begin our paper with a discussion of the data source, the methodologies employed in the original paper and a review of the variables used for our reproduction. We will then conduct a reproduction of select results to verify their findings and improve upon their accessibility. Our paper will conclude with a discussion of our findings where we conduct a case study to apply our findings to Alberta, Canada's only Province with a greater population of males, a discussion of ethical biases, limitations and a push for future research.

# Data

## Source

In this paper we aim to replicate part of the results from the "How Terrorism Does (and Does Not) Affect Citizens’ Political Attitudes: A Meta-Analysis." In the original paper, the author Godefroidt explored the correlation between terrorism and outgroup hostility and conservatism. Furthermore, the author also included more complicated models and even an shinny app for interactive viewing. Due to various restraints, we are going the test the major finding of the original paper.

In summary, the major claims(also what we are gong to replicate ) of the original paper are:
1.To what extend do terrorism arose public sentiment towards outgroup hostility, and a conservative shift. 
2.To what extend do the last claim hold, if being placed across different contexts.How such differences in observed effect sizes explained by additional moderators?

## Methodology

The original paper obtained its data from database that contains 12333 records. The data was collected throug three steps, electronic search, screening related paper, and public survey. After the filtering, 10,391 records were included for further reviewing. In the [figure 1], the author used a flow chart to illustrate the collecting and cleaning process. The collected data from six sources ranging from 'web of science,' to 'personal contact.' After preliminary filtering, additional 9444 records were removed due to the nature of these information are news articles and policy briefing. The inclusion of these information may ditch the reliability of the analysis. Eventually 241 pieces were retained. They were then used for data processing, a total of 1733 total associations were generated. 

## Features

Those associations or processed data are stored in the file metaanalysis-data.xlsx. It contains 76 column and 1733 observations. A randomized selection of manuscripts (±15% of the total sample) was used to pilot the code book and make any necessary revisions. The columns can be divided into fifth major data categories. The first part of the variables are identity information of the data such as the author name, year of the study, the sample size and the general population. The second part is the political tendency and people's ethnicity with variables ranging from the percentage of people identifying as a liberal and mean to the white-muslims percentage. The third portion records the detail of each terrorist attack, including the type, date, casualties. The forth part records a series of political attitudes. For example, nationalism and institutional trust, socio-economic conservatism, support for policies that pertains an outgroup. The last part lists the analysis technical data that will be used in meta-analysis code such as Fisher's Z correlation, Regression and so on. From the original survey data, each variable correlates with a survey question asked to participants. In our reproduction, we excluded data that being used for figure3 and figure4 the moderator test. We also made some minor changes and removed insignificant data for clearer replication and viewing. 

In order to better present our replication of the results, The following are measurments of public political opinions provided by the author. They are classfied into 4 categories given in the orignal paper. We selected some important measures 

[Objective exposure]{.underline}

-   Pre postattack measures
-   Days between an act of violence and survey day
-   Newspaper vignette about an act of violence
-   News clip about an act of violence

[Self-reported exposre]{.underline}

-   Direct exposure to terrorism
-   Indirect exposure via friends and family
-   Indirect exposure via media reports

[Cognitions]{.underline}

-   Self-reported concern/worry for an attack on the nation
-   Self-reported concern/worry to become a victim of terrorism
-   Self-reported concern/worry for an attack on the nation
-   Manipulated vignette or writing task about the threat of terrorism (rather than about a specific act of violence)
-   Manipulated percentage of the threat of terrorism

[Emotion]{.underline}

-   Anger/outrage
-   Fear/anxiety
-   Sadness
-   General negative emotion

# Statistical Analysis

In this paper we will replicate figure 2 and table2 of the orginal paper. Fortunately, the author has already compressed all the analysis into one coding file. We selected the corresponding part for each illustration. In terms of the analysis method, Pearson's correlation coefficient is used. According to the orignal paper, the manuscripts of the data they collected used various statistical method. For comparison purposes, each association is converted into a Pearson's correlation coefficient with the sampling variance. The author stressed that to "meaningfully compare and pool effect sizes, all correlations must also reflect the relation between terrorism and sociopolitical attitudes in the same direction."


# Results


As depicted in @fig-collection(A) and (B), scholarly interest in exploring the link between terrorism and public attitudes notably began following the 9/11 attacks, and received further impetus following the 2015–16 Islamic State (IS) attacks. Put differently, the figures imply that this research domain is significantly influenced by specific events.


Moreover, from 1985 to 2020, researchers have employed diverse methodologies to measure exposure to terrorism (refer to @fig-collection(C)). Some studies exposed participants to news articles or video clips depicting specific acts of violence (e.g., 9/11), while in other cases, exposure occurred naturally when surveys coincided with terror attacks (527 data points of acts of violence , as 30%). Additionally, studies have assessed or manipulated individuals' perceptions of terrorism threats (threat of violence: 520 data points as 30%), examined affective responses such as fear (146 data points) and anger (111 data points), and investigated self-reported exposure to terrorism through personal experiences, relatives' experiences, or media coverage (self-reported exposure: 184 data points).

The most frequently studied acts of violence are—perhaps unsurprisingly—9/11, the Israeli-Palestinian conflict, and the 2015 series of IS attacks in Paris. Consequently, regarding the ideology behind the violence (@fig-collection(D)), the vast majority of effect sizes quantify the effects of or relationship with Islamist terrorism (1,064 data points, 61%), following by no ideology terrorism, whereas the share of information on how the public reacts to extreme-right terror is remarkably low (35 data points, 2%).


Table 1 demonstrates that...




\clearpage




# Discussion

## Findings

In this paper, we have replicated the results found by Dancygier, Egami, Jamal, and Rischke. Their analysis sought to explore the correlation between perceived mate competition in municipalities with excess males and its contributions to anti-refugee sentiments and higher crime rates in Germany. Our paper has replicated two of their major findings.

(1) Non-immigrant German men who live in municipalities with excess male populations are more likely to perceive refugees as threats.

(2) Non-immigrant German men who perceive mate competition are more likely to support violence as the only means to gain the attention of German politicians.

By replicating their results, we hope to apply a Canadian-facing lens to gain insights into Canadian dating markets, the geographical distribution of males and females and their potential impacts on anti-refugee sentiments.

## Canadian Relevance: Case Study on Alberta's population ratios, dating markets and anti-refugee sentiments

To investigate the relevance of Dancygier, Egami, Jamal, and Rischke's discoveries in a Canadian context, we will now explore Canada's only Province with a higher ratio of males than females. 

Alberta is a Province in Canada with a total population of 4,543,111 individuals. It is the only Canadian Province that is more heavily populated by males, with a male population of 2,282,040 compared to 2,261,071 females [@statista]. Thus having a ratio of approximately 1.01, which is comparable to that of the 1st tercile in Figure 1. This means that there are about 11,000 more men than women residing in this Province. Part of the population gap can be explained by age. Alberta has a primarily young population and we typically see that as populations age they exhibit a higher female population [@edmonton_journal]. Its trades centric economy also attracts young male migrants from across Canada [@edmonton_journal]. 

Concerning the original paper, Alberta's population growth can be largely attributed to international immigration which has typically brought equal numbers of males and females [@edmonton_journal]. However, according to the 2021 census, 101, 650 more males are single (not married or living common law and never married) than women [@govcan]. Due to Alberta's young population, highly concentrated with men of working age, a comparison can be made to the term 'mating-aged' used in the original paper to describe males facing higher tensions of dating competition. We thus believe that similar conditions for dating and marriage markets can be made between Alberta and the German municipalities of that the 1st Tercile from Figure 1. 

While population demographics are comparable between that of Alberta and the 1st tercile of German municipalities in the original paper, it is difficult to suggest that potential competition in Albertan dating and marriage markets correlates to anti-refugee sentiments and violence. However, in addressing Albertan immigrant and refugee statistics we will aim to illustrate how these patterns found in Germany can manifest in the context of Alberta. Based on the 2021-2022 Annual Population Report, Alberta welcomed 12,603 immigrants and 21,434 non-permanent residents, which include refugees [@alberta_2023]. 

While previous accounts have suggested that immigration has brought an equal number of males and females, it is safe to assume that Alberta is a growing population, subject to a population with a higher concentration of males [@edmonton_journal]. According to a 2018 paper, at the time 6 in 10 Canadians disagreed when asked if immigration levels were too high, with 35% believing that Canada accepts too many immigrants [@globe_mail]. However, sentiments appear less than positive in Alberta, with Albertans expressing harsher attitudes towards immigrants and refugees [@globe_mail]. 48% of Albertans at the time agreed that refugee claims are not filed from real refugees, with 62% stating that immigrants do not adopt Canadian values, about 10% higher than the national average of 51% [@globe_mail]. The Globe and Mail suggest that part of Alberta's higher anti-refugee attitudes can be attributed to its economy and fears of competition.Dancygier, Egami, Jamal, and Rischke  find that in areas where men significantly outnumber women, there are higher levels of anti-refugee hate crimes [@main_paper]. 

Based on these statistics, we believe that Alberta may experience a similar effect of anti-refugee sentiments in part as a result of increased immigrants/ refugees and competition in a young male-dominated population. However, as stated in their original paper, we call for further research to be conducted on this effect to better understand its implications on non-German countries.

## Ethical Implications

In their paper, Dancygier, Egami, Jamal, and Rischke examine the ethical implication of using experimental methodologies to investigate their research topic. By using descriptive data in the form of surveys they are able to investigate the opinions of non-immigrant German males and their perception of mate competition and its translation to anti-refugee violence. By avoiding experimental trials, they were able to explore their topic without provoking anti-refugee sentiment [@main_paper]. While conducting experimental trials on this topic of research is considered unethical, surveys and questionnaires may have a tendency to give respondents the impression that their opinions are commonly shared or even accurate. By being presented with a platform to express their perception of mate competition and if they agree that violence towards refugees is the only way to garner the attention of German politicians, respondents may feel that their opinions are incorrectly justified. This then has the potential to translate to violence towards German refugees.

## Accounting for Bias

Ethical implications and biases arise naturally when collecting quantitative and qualitative data. In their paper, Dancygier, Egami, Jamal, and Rischke use online survey platforms to assess if Germans living in areas with greater populations of men who experience turmoil in the mating market are more likely to perceive competition between themselves and refugees, moreover, does this ideology predict hate crime support [@main_paper]. The authors attempted to address ethical concerns and statistical biases by utilizing control groups and replicating their study with different samples and polling firms. However, one potential bias that is challenging to control for is the presence of sampling bias [@main_paper]. Sampling bias occurs when participants in a study are not representative of the estimand or the ideal population of interest. One method to control for this bias is simple random sampling, where participants are chosen by chance. Meaning that every individual in the population has an equal chance of being selected. However, in their study, they were unable to utilize simple random sampling. Instead attempted to make their survey results representative by conducting 4 waves of surveys meant to be representative of age, gender and geographical region [@main_paper]. Despite their effort, their survey results may not be entirely representative as individuals who have a strong interest in the subject matter are more likely to participate, meaning they do not reflect the views of all non-immigrant German males [@main_paper].

## Limitations

Being a reproduction, much of our analysis was limited to the original survey circumstances captured in [@main_paper]. Despite the survey being long, it can not be considered to be comprehensive. This prevented us from exploring other relationships in the data. For example, in this German context, it would have been interesting to look into sentiments toward the treatment of communities experiencing genocide during the history of World War 2. Our connection of findings to the Albertan context was also limited by this cultural and geographical separation from our data.

Due to the heteronormative nature of this study's data, our analysis was also not able to be fully representative of the German population as [@main_paper]'s authors described. While this is not to be surprised from an ecological context of mating behaviour, perhaps gay men would have been found to experience anti-refugee sentiment as well as an extension of the mate competition argument.

There were also limitations associated with missing and limited data in our set. For example, in our analysis depicted in @fig-excess, fewer than 300 observations were represented in the oldest age group, which these authors doubted was enough for a meaningful evaluation.

## Future Research

As suggested in their original paper, Dancygier, Egami, Jamal, and Rischke call for future research to investigate how their findings apply to less ethnically distinct groups, with less aggressive media attention and under non-heteronormative roles [@main_paper]. They further call for tests in ethnonational countries and in regions where females overpopulate males to see if their findings apply to women [@main_paper]. As Global migration and refuge continue to increase, we anticipate that this field of study will become increasingly significant. It is thus crucial to expand on their findings to assess how they apply in varying nations. This is in hopes to create policy changes and account for preventative measures to avoid increased anti-refugee sentiments and hate crimes caused by sex-driven competition. We further hope for this field of research to be applied under less heteronormative circumstances and work to account for queer-identifying individuals.

\clearpage

# References {.unnumbered}
